# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obvestilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besedilo', models.CharField(max_length=500)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uporabnisko_ime', models.CharField(max_length=20)),
                ('geslo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='obvestilo',
            name='avtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trener.Trener'),
        ),
    ]
